function Hd = BP_FIR_50_Hamming_11792_710_750
%BP_FIR_50_HAMMING_11792_710_750 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 09-May-2024 23:10:50

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 11792;  % Sampling Frequency

N    = 50;       % Order
Fc1  = 710;      % First Cutoff Frequency
Fc2  = 750;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
