function Hd = BP_IIR_60_Butter_5896_385_675
%BP_IIR_60_BUTTER_5896_385_675 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 08-May-2024 01:19:51

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 5896;  % Sampling Frequency

N   = 60;   % Order
Fc1 = 385;  % First Cutoff Frequency
Fc2 = 675;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');


% [EOF]
